### ISSUE TITLE
Error trying to run .NET  9 Android

### ISSUE THREAD

**Issue by Saccomani** [marcojak/MauiMTAdmob#113]
I just install the package and try to run on my emulator, its showing this message, if I remove, the build works!

  Error in obj/Debug/net9.0-android/lp/216/jl/classes.jar:androidx/work/CoroutineWorker$getForegroundInfoAsync$1.class:
Type androidx.work.CoroutineWorker$getForegroundInfoAsync$1 is defined multiple times: obj/Debug/net9.0-android/lp/216/jl/classes.jar:androidx/work/CoroutineWorker$getForegroundInfoAsync$1.class, obj/Debug/net9.0-android/lp/235/jl/classes.jar:androidx/work/CoroutineWorker$getForegroundInfoAsync$1.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj/Debug/net9.0-android/lp/216/jl/classes.jar
androidx/work/CoroutineWorker$getForegroundInfoAsync$1.class
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:131)
	at com.android.tools.r8.D8.main(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:5)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj/Debug/net9.0-android/lp/216/jl/classes.jar:androidx/work/CoroutineWorker$getForegroundInfoAsync$1.class
	at Version.fakeStackEntry(Version_8.5.35.java:0)
	at com.android.tools.r8.T.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:5)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:82)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:32)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:31)
	at com.android.tools.r8.internal.to.b(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:2)
	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:41)
	at com.android.tools.r8.D8.b(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:13)
	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:39)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:118)
	... 1 more
Caused by: com.android.tools.r8.internal.g: Type androidx.work.CoroutineWorker$getForegroundInfoAsync$1 is defined multiple times: obj/Debug/net9.0-android/lp/216/jl/classes.jar:androidx/work/CoroutineWorker$getForegroundInfoAsync$1.class, obj/Debug/net9.0-android/lp/235/jl/classes.jar:androidx/work/CoroutineWorker$getForegroundInfoAsync$1.class
	at com.android.tools.r8.internal.x50.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:21)
	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:54)
	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2056)
	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:6)
	at com.android.tools.r8.graph.p4$a.d(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:6)
	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:95)
	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:44)
	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:9)
	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:44)
	at com.android.tools.r8.D8.d(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:17)
	at com.android.tools.r8.D8.c(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:73)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:28)
	... 6 more
O diretório 'obj/Debug/net9.0-android/lp/216' é de 'androidx.work.work-runtime.aar'.
O diretório 'obj/Debug/net9.0-android/lp/235' é de 'androidx.work.work-runtime-ktx.aar'.

**Comment by chrmeehansr** [comment]
Were you able to resolve? I've been struggling with a similar output. While I'm learning how much of a challenge the transitive dependencies are.. it's infuriating.  Here's my output for comparison and others. Targeting .net9.0 but also couldn't get past this with .net8.0. I've tried tracing and modifying the various dependency builds with no success. Any help if anyone has any thoughts would be greatly appreciated. 

I've also tried the guidance here.. https://www.mauiexpert.it/admob-for-maui-made-easy/ and added the user-messaging-platform-2.0.0.aar as noted. 

1>MSBUILD : java.exe error JAVA0000: Error in obj\Debug\net9.0-android\lp\383\jl\classes.jar:com/google/android/gms/internal/measurement/zzfs.class:
1>MSBUILD : java.exe error JAVA0000: Type com.google.android.gms.internal.measurement.zzfs is defined multiple times: obj\Debug\net9.0-android\lp\383\jl\classes.jar:com/google/android/gms/internal/measurement/zzfs.class, obj\Debug\net9.0-android\lp\384\jl\classes.jar:com/google/android/gms/internal/measurement/zzfs.class
1>MSBUILD : java.exe error JAVA0000: Compilation failed
1>MSBUILD : java.exe error JAVA0000: java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\net9.0-android\lp\383\jl\classes.jar
1>MSBUILD : java.exe error JAVA0000: com/google/android/gms/internal/measurement/zzfs.class
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:131)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.main(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:5)
1>MSBUILD : java.exe error JAVA0000: Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\net9.0-android\lp\383\jl\classes.jar:com/google/android/gms/internal/measurement/zzfs.class
1>MSBUILD : java.exe error JAVA0000: 	at Version.fakeStackEntry(Version_8.5.35.java:0)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.T.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:5)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:82)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:32)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:31)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.to.b(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:2)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:41)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.b(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:13)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:39)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:118)
1>MSBUILD : java.exe error JAVA0000: 	... 1 more
1>MSBUILD : java.exe error JAVA0000: Caused by: com.android.tools.r8.internal.g: Type com.google.android.gms.internal.measurement.zzfs is defined multiple times: obj\Debug\net9.0-android\lp\383\jl\classes.jar:com/google/android/gms/internal/measurement/zzfs.class, obj\Debug\net9.0-android\lp\384\jl\classes.jar:com/google/android/gms/internal/measurement/zzfs.class
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.x50.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:21)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:54)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:10)
1>MSBUILD : java.exe error JAVA0000: 	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2056)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:6)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.graph.p4$a.d(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:6)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:95)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:44)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:9)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:44)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.d(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:17)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.c(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:73)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:28)
1>MSBUILD : java.exe error JAVA0000: 	... 6 more
1>MSBUILD : java.exe error JAVA0000: Directory 'obj\Debug\net9.0-android\lp\383' is from 'play-services-measurement-base.aar'.
1>MSBUILD : java.exe error JAVA0000: Directory 'obj\Debug\net9.0-android\lp\384' is from 'play-services-measurement.aar'.

**Comment by moljac** [comment]
Please check

https://github.com/dotnet/android-libraries/issues/764

**Comment by AndreasReitberger** [comment]
Same problem on my side..
I fixed it with adding a this to my `.csproj`

```xml
<ItemGroup Condition="$(TargetFramework.Contains('android'))>
     <PackageReference Include="Xamarin.AndroidX.SavedState.SavedState.Ktx" Version="1.3.1" /> 
    <PackageReference Update="Xamarin.AndroidX.SavedState.SavedState.Android">
    	<ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
</ItemGroup>
```

I'm not sure if this is the right way, but it builds.

**Comment by AntHillOracle** [comment]
I also have this "package outside of dependency constraint" problem when building using MauiMtAdmob 2.2 for android.  My java compilation error looks slightly different I think, but adding the PackageReference noted by Andreas does allow the compile to succeed.  However, I still get 10 dependency constraint warnings.

Using 2.2 my app is crashing when built in Release mode whenever an interstitial is requested to be shown.  This happens on android and iOS.  I'll try to collect more information about the crash and report in a seperate issue.
